name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get version
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # Strip the 'v' prefix for CMake compatibility but keep it for filenames
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "FILE_VERSION=v${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=1.0.2-dev" >> $GITHUB_OUTPUT
          echo "FILE_VERSION=v1.0.2-dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libwxgtk3.0-gtk3-dev nlohmann-json3-dev nmap
        
    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      
    - name: Build and Install
      working-directory: build
      run: |
        cmake --build .
        
        # Create necessary directories
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps
        mkdir -p AppDir/usr/share/PingCCXPool/resources
        
        # Copy binary and json file
        cp bin/* AppDir/usr/bin/
        # Set ownership to nobody:nogroup for read-only data files
        sudo chown nobody:nogroup AppDir/usr/bin/pools.json AppDir/usr/bin/pp.png
        
        # Copy and setup AppRun script
        cp ../AppRun AppDir/AppRun
        chmod +x AppDir/AppRun
        
        # Process desktop file template
        cp ../PingCCXPool.desktop.template AppDir/usr/share/applications/PingCCXPool.desktop
        sed -i "s/VERSION_X/${{ steps.get_version.outputs.VERSION }}/g" AppDir/usr/share/applications/PingCCXPool.desktop
        
        # Copy icons for desktop integration
        cp ../pp.png AppDir/usr/share/icons/hicolor/256x256/apps/PingCCXPool.png
        cp ../pp.png AppDir/usr/share/icons/hicolor/128x128/apps/PingCCXPool.png
        
        # Copy policy file for manual installation
        cp ../org.acktarius.nping.policy AppDir/usr/share/PingCCXPool/resources/
        
    - name: Download linuxdeploy
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        
    - name: Create AppImage
      working-directory: build
      run: |
        # Create AppImage using explicit flags for better control
        ../linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
          --desktop-file AppDir/usr/share/applications/PingCCXPool.desktop \
          --icon-file AppDir/usr/share/icons/hicolor/256x256/apps/PingCCXPool.png \
          --output appimage
        
        # Rename and create MD5
        mv PingCCXPool*.AppImage PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage
        md5sum PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage > PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage.md5
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64
        path: |
          build/PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage
          build/PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage.md5
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage
          build/PingCCXPool-${{ steps.get_version.outputs.FILE_VERSION }}-ubuntu22.04-x86_64.AppImage.md5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 